let people:string[] = [ 'Rehan', 'Hazim', 'Zia', 'Shahzaib', 'Umer', 'Abid' ];
console.log(people);
people.pop();
people.pop();
people.pop();
people.pop();
console.log("These people are still invited");
console.log(people);
people.pop();
people.pop();
console.log(people);
